version: '3.1'

services:

  wordpress:
    image: docker.io/wordpress:6.0.1-apache
    container_name: wp-ll
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: docker.io/mariadb:10.7.4-focal
    container_name: db-ll
    restart: always
    environment:
      MARIADB_DATABASE: exampledb
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      MARIADB_ROOT_PASSWORD: '1'
    volumes:
    - ../mysql:/var/lib/mysql:rw

  # db:
  #   image: mysql:8.0.29-debian
  #   container_name: db-ll
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: exampledb
  #     MYSQL_USER: exampleuser
  #     MYSQL_PASSWORD: examplepass
  #     MYSQL_RANDOM_ROOT_PASSWORD: '1'
  #   volumes:
  #   - ../mysql:/var/lib/mysql:rw
