SHELL := /bin/bash
.PHONY: help

wp-db-logs:
	@./Make.sh _wp_db_logs

wp-db-shell:
	@./Make.sh _wp_db_shell

wp-wp-logs:
	@./Make.sh _wp_wp_logs

wp-wp-shell:
	@./Make.sh _wp_wp_shell

wp-down:
	@./Make.sh _wp_down

wp-stop:
	@./Make.sh _wp_stop

wp-up:
	@./Make.sh _wp_up
