SHELL := /bin/bash
.PHONY: help

container-db-logs:
	@./Make.sh _container_db_logs

container-db-shell:
	@./Make.sh _container_db_shell

container-wp-logs:
	@./Make.sh _container_wp_logs

container-wp-shell:
	@./Make.sh _container_wp_shell

containers-down:
	@./Make.sh _containers_down

containers-stop:
	@./Make.sh _containers_stop

containers-up:
	@./Make.sh _containers_up
